### PR TITLE
Paged content config

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/932

* Test with https://github.com/Islandora-Devops/claw-playbook/pull/143

# What does this Pull Request do?

Adds the IIIF manifest view and the openseadragon block and wires it up to for 'Paged Content' using context.  I also tossed half of the `islandora_core_feature` in here since it was introducing dependencies on `islandora_defaults`

# What's new?
- A lot of config from the core feature moved over as-is
- The IIIF manifest view
- The openseadragon block
- An 'Openseadragon Block' context that displays it for paged content

# How should this be tested?

See https://github.com/Islandora-Devops/claw-playbook/pull/143

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Waaaaaiiiit..... shouldn't that view be using the URIs, @dannylamb, so we don't lock a dependency on the term's uuid/tid?

**Comment by dannylamb** [comment]
Nooooooooooooo.....  but yes.  Maybe I can make a views filter views and wrap the existing NodeHasTerm condition.

**Comment by dannylamb** [comment]
Bwahahaha, or I can just use a relationship on the media use taxonomy term and actually check the link as a string.

**Comment by dannylamb** [comment]
Yes, that works and removes the dependency.  Views FTW.  I'm playing around with the features file right now to add some thing to the ignore list, otherwise they keep popping back up on you in the UI.  They'll sneak back in eventually if I don't sort this out.

**Comment by dannylamb** [comment]
@seth-shaw-unlv NM, i was on a different branch for islandora than islandora_defaults to test something and it looked like the features UI auto-added things back in.  Operator error.

I've updated PR to eliminate the dependency on the taxonomy term, instead using a views relationship to check the uri as a string.  Good catch and fortunately easy fix!

**Comment by whikloj** [comment]
@dannylamb I think this is good, but we seem to have a lot of configs that are now relying on config that is in islandora_core_feature (`modules/islandora_core_feature/config/install/taxonomy.vocabulary.islandora_media_use.yml`, I'm looking at you), so should the dependency here be to islandora_core_feature which in turn depends on islandora?

**Comment by whikloj** [comment]
Travis is missing some block config
```
Configuration objects provided by islandora_search have unmet dependencies: 
block.block.exposedformsolr_search_contentpage_1 (carapace)
```
Which I think is because we just removed it from the [Travis setup](https://github.com/Islandora-CLAW/CLAW/pull/1292). Perhaps we need to `composer require islandora/carapace` to ensure it is installed.

**Pull request merged**
